version: "3"
networks:
    web:
        external: true
services:
    server:
        image: haidousm/traefiker-server:SNAPSHOT
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - web
        ports:
            - 8010:8010
    client:
        image: haidousm/traefiker-client:SNAPSHOT
        networks:
            - web
        environment:
            - NEXT_PUBLIC_API_URL=http://192.168.0.171:8010
        ports:
            - 8020:8020
