version: "3"
networks:
    web:
        external: true
services:
    server:
        image: haidousm/traefiker-server:SNAPSHOT
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - web
        ports:
            - 8010:8010
        labels:
            - traefik.http.routers.traefiker-server.tls=true
            - traefik.http.routers.traefiker-server.tls.certresolver=lets-encrypt
    client:
        image: haidousm/traefiker-client:SNAPSHOT
        networks:
            - web
        ports:
            - 8020:8020
        labels:
            - traefik.http.routers.traefiker-client.tls=true
            - traefik.http.routers.traefiker-client.tls.certresolver=lets-encrypt
