version: "3"
networks:
  web:
    external: true
services:
  web:
    image: haidousm/traefiker-client:SNAPSHOT
    labels:
      - traefik.http.routers.web.rule=Host(`admin.localhost`)
    networks:
      - web
  api:
    image: haidousm/traefiker-api:SNAPSHOT
    labels:
      - traefik.http.routers.api.rule=Host(`admin.localhost`) && PathPrefix(`/api`)
      - traefik.http.middlewares.api-prefix.stripprefix.prefixes=/api
      - traefik.http.routers.api.middlewares=api-prefix
    networks:
      - web