version: "3"
networks:
    web:
        external: true
services:
    traefiker-server:
        image: haidousm/traefiker-server:v1.2.0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - web
        ports:
            - 8010:8010
        labels:
            - traefik.http.routers.server.tls=true
            - traefik.http.routers.server.tls.certresolver=lets-encrypt
    traefiker-client:
        image: haidousm/traefiker-client:v1.2.0
        networks:
            - web
        ports:
            - 8020:8020
        labels:
            - traefik.http.routers.client.tls=true
            - traefik.http.routers.client.tls.certresolver=lets-encrypt
