name: Build & Deploy Prod. Docker Image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:

  docker:
    name: Build And Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag haidousm/traefiker:SNAPSHOT
    - name: Push the Docker Image to DockerHub
      run: |
        docker push haidousm/traefiker:SNAPSHOT

  # deploy:
  #   name: Deploy Prod. Docker Image
  #   runs-on: ubuntu-latest
  #   needs: [ docker ]
  #   steps:
  #   - name: Call Webhook
  #     uses: joelwmale/webhook-action@master
  #     env:
  #       WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
      
